steps:
  remote-build:
    image: rafaelsgirao/nix-remote-builder-plugin:latest
    pull: true
    settings:
      hostname: 192.168.10.6
      sshport: 22
      username: nixremote
      sshkey:
        from_secret: nixremote_sshkey
      flakepaths: >-
        .#nixosConfigurations.scout.config.system.build.toplevel,
        .#nixosConfigurations.spy.config.system.build.toplevel
        .#nixosConfigurations.saxton.config.system.build.toplevel

