steps:
  remote-build:
    image: johnwalkerx/nix-remote-builder-plugin:latest
    pull: true
    settings:
      hostname: cache.spy.rafael.ovh
      sshport: 22
      username: nixremote
      sshkey:
        from_secret: nixremote_sshkey
      flakepaths: >-
        .#nixosConfigurations.scout.config.system.build.toplevel,
        .#nixosConfigurations.spy.config.system.build.toplevel
        .#nixosConfigurations.saxton.config.system.build.toplevel

