steps:
  verify:
    # when:
    #   event: [ pull_request ]
    image: debian:latest
    # image: nixpkgs/nix:nixos-23.11
    # image: nixpkgs/bash
    commands:
    - apt update && apt install curl -y
    -  curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm --init none
    - nix --version
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix flake show



# pipeline:
#   first-job:
#     image: lnl7/nix:latest
#     commands:
#       - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
#       - nix flake check 


# pipeline:
#   flake-check:
#     image: nixos/nix
#     commands:
#       # - nix flake check --experimental-features flakes --experimental-features nix-command
# pipeline:
#   flake-check:
#     image: nixos/nix
#     commands:
#       - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
#       # - nix flake check
#       - nix flake check --store unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt
#       - nix run --store unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt .#build-all
#     volumes:
#       - /nix:/mnt/nix:ro
