pipeline:
  first-job:
    image: bash
    commands:
      - echo "first run"


# pipeline:
#   flake-check:
#     image: nixos/nix
#     commands:
#       # - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
#       # - nix flake check --experimental-features flakes --experimental-features nix-command
# pipeline:
#   flake-check:
#     image: nixos/nix
#     commands:
#       - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
#       # - nix flake check
#       - nix flake check --store unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt
#       - nix run --store unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt .#build-all
#     volumes:
#       - /nix:/mnt/nix:ro
