---
name: CI
on: push

env:
  USER: gitea-runner

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    # container:
    #   image: "nixos/nix"
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Install Nix ❄️ " 
        uses: cachix/install-nix-action@v18
      - uses: DeterminateSystems/magic-nix-cache-action@main
        name: "Magic Nix Cache!"
      - run: nix flake check --no-build --extra-experimental-features "nix-command flakes"
        name: Run nix flake checks
